from email.message import EmailMessage
import smtplib

EMAIL = "subhayu.roy2001@gmail.com"  #Your email-id
PASSWORD = "***********"  #Your email-id password

msg = EmailMessage()

msg['Subject'] = 'Email using python'  #Subject
msg['From'] = EMAIL  #Sender's email
msg['TO'] = ['myfriend@gmail.com']  #Receiver's email

message = "This is a sample email which I, Subhayu is using to send an attachment to someone. This generated by Python3"
msg.set_content(message)

attachment = ['/home/subhayu_roy/virus.bat']  #List of attachment files

for path in attachment:
    with open(path, 'rb') as file:
        data = file.read()
        name = path.split("/")[-1]

    msg.add_attachment(data, maintype = 'application', subtype = 'octet-stream', filename = name)

with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
    smtp.login(EMAIL, PASSWORD)
    smtp.send_message(msg)